### ISSUE TITLE
Missing to load defs on fly

### ISSUE THREAD

**Issue by wohnout** [proj4js/proj4js#165]
Hi,
in older version of proj4js was possibility to load defs on fly. Function first lookup to defs folder and then to spatialreference.org (by default now is more used eps.io i think) for definition

This was done by this code

```
/**
 * Function: loadProjDefinition
 *    Loads the coordinate system initialization string if required.
 *    Note that dynamic loading happens asynchronously so an application must 
 *    wait for the readyToUse property is set to true.
 *    To prevent dynamic loading, include the defs through a script tag in
 *    your application.
 *
 */
    loadProjDefinition: function() {
      //check in memory
      if (Proj4js.defs[this.srsCode]) {
        this.defsLoaded();
        return;
      }

      //else check for def on the server
      var url = Proj4js.getScriptLocation() + 'defs/' + this.srsAuth.toUpperCase() + this.srsProjNumber + '.js';
      Proj4js.loadScript(url, 
                Proj4js.bind(this.defsLoaded, this),
                Proj4js.bind(this.loadFromService, this),
                Proj4js.bind(this.checkDefsLoaded, this) );
    },

/**
 * Function: loadFromService
 *    Creates the REST URL for loading the definition from a web service and 
 *    loads it.
 *
 */
    loadFromService: function() {
      //else load from web service
      var url = Proj4js.defsLookupService +'/' + this.srsAuth +'/'+ this.srsProjNumber + '/proj4js/';
      Proj4js.loadScript(url, 
            Proj4js.bind(this.defsLoaded, this),
            Proj4js.bind(this.defsFailed, this),
            Proj4js.bind(this.checkDefsLoaded, this) );
    },

```

Why was this functionality dropped?

**Comment by calvinmetcalf** [comment]
- so that this library wouldn't be tied to a specific website or service that was not affiliated with this library (if it had been kept in you'd be stuck with spatialreference.org in all likelihood) 
- because any sort of loading would by asynchronous despite every other part of this being syncrounous
- because most non-demo uses of this library only require 1 or 2 epsg codes which the developer, in all likelihood, has the def locally.
- because the previous version wouldn't work in node.js (and was the sole thing that wouldn't work in both places).
- because anyone who really wants the functionality can write a plugin or library to do it pretty easily (this could be you)
