### ISSUE TITLE
EPSG:3857 TO EPSG:4326 using  wkt of EPSG:3857 problem ?

### ISSUE THREAD

**Issue by saidaipparla** [proj4js/proj4js#220]
FirstConversion: EPSG:3857 TO EPSG:4326 using 
wkt of EPSG:3857 & proj4 of EPSG:4326(unExpected)

-112.50042920000004,42.228291640899414

SecondConversion: EPSG:3857 TO EPSG:4326 using 
proj4 of EPSG:3857 & proj4 of EPSG:4326(Expected)

-112.50042920000004,42.036926809999976

here is the sample:
https://jsfiddle.net/saisoft00/c7vecefz/13/

**Comment by calvinmetcalf** [comment]
An issue with the wkt parsing so use the proj strings, or even better both
of those are included CRSs

**Comment by offtherailz** [comment]
Yes, it seems to be that. We found this issue using https://github.com/calvinmetcalf/shapefile-js . I see you @calvinmetcalf are the author of this lib so is not not needed to explain it parses the WKT from prj file :).

**Comment by calvinmetcalf** [comment]
ah I see, so the root issue is that the wkt parser I wrote is somewhat imperfect mainly due to wkt for projections being one of the worst formats I have ever had to work with, deal with, or hear about, with at least 3 mutually incomparable implementations in wide use.

currently we have a naive parser with a bunch of hand coded exceptions but that needs to be rewritten.

**Comment by calvinmetcalf** [comment]
I've pulled [the parser out into it's own repo](https://github.com/proj4js/wkt-parser) to try to hack on it if I have time or for others to try to improve it.

**Comment by MV88** [comment]
Hi @calvinmetcalf are you suggesting to use proj strings instead of the wkt ones?
if so, how can I change the shapefile in order to use the proj string?  should I modify the .prj file?

**Comment by calvinmetcalf** [comment]
if you've got a specific problematic proj file we can see about fixing stuff, but generally yeah the proj strings do work better if you have a choice in the matter.

**Comment by calvinmetcalf** [comment]
if you've got a specific problematic proj file we can see about fixing stuff, but generally yeah the proj strings do work better if you have a choice in the matter.

**Comment by mbarto** [comment]
Hi, we went deeper in analyzing this. We found a couple of issues with this prj file:

PROJCS["WGS 84 / Pseudo-Mercator", GEOGCS["WGS 84", DATUM["World Geodetic System 1984", SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], AUTHORITY["EPSG","6326"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic latitude", NORTH], AXIS["Geodetic longitude", EAST], AUTHORITY["EPSG","4326"]], PROJECTION["Popular Visualisation Pseudo Mercator", AUTHORITY["EPSG","1024"]], PARAMETER["semi_minor", 6378137.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["Easting", EAST], AXIS["Northing", NORTH], AUTHORITY["EPSG","3857"]]

The first issue is that the authority (EPSG:3857) is not coherent with the DATUM (WGS84).
The second issue is that if we fix the PRJ, changing the DATUM rf parameter to 0 instead of 298.xxx the parsed datum_type is incorrect. I would like to prepare a PR to:
 * change the WKT parser to trust the AUTHORITY of if present in WKT and a definition for the (EPSG) code is defined in proj4js
 * set datum_type to NODATUM if sphere: true is defined

Is this acceptable?

**Comment by calvinmetcalf** [comment]
the parser doesn't look up anything external when parsing the proj so it can't look up anything external so the first thing isn't really possible and we basically ignore the authority codes and I'm not sure about the other one can you give me an example of a well formed (e.g. non hand edited) proj file where that might come up?

**Comment by mbarto** [comment]
PROJCS["WGS 84 / Pseudo-Mercator", GEOGCS["WGS 84", DATUM["World Geodetic System 1984", SPHEROID["WGS 84", 6378137.0, 0, AUTHORITY["EPSG","7030"]], AUTHORITY["EPSG","6326"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic latitude", NORTH], AXIS["Geodetic longitude", EAST], AUTHORITY["EPSG","4326"]], PROJECTION["Popular Visualisation Pseudo Mercator", AUTHORITY["EPSG","1024"]], PARAMETER["semi_minor", 6378137.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["Easting", EAST], AXIS["Northing", NORTH], AUTHORITY["EPSG","3857"]]

**Comment by calvinmetcalf** [comment]
so it looks like the esri version of 3857 is fine but the ogc one never mentions that it's on a sphere, we may have to put a special case for 3857 in the lib as it is one that we actually include
