### ISSUE TITLE
Using EPSG:5513 WKT from epsg.io produces incorrect result

### ISSUE THREAD

**Issue by JackClouseau** [proj4js/proj4js#445]
I am trying to transform a test point from lat 50 degrees N, long 14 degrees E (WGS84) to EPSG:5513 (Czech Republic).
Proj4js produces negative values   [-774047.4656886813, -1048457.5530448735]
EPSG:5513 should always produce positive values.

Please note:  EPSG:5514 should always produce negative values.  It produces  [-774047.4656886813, -1048457.5530448735]  at the same test point.  This is correct.

This might have been an issue in proj.4 and I think there was a fix for it in proj.7.
Any chance we can get the fix in Proj4js?

**Comment by ahocevar** [comment]
Currently proj4js only respects axis order, not axis orientation (see https://github.com/proj4js/proj4js#axis-order). As far as I can tell, 5513 uses `swu` axis orientation, and is identical to 5514 (`enu` default axis orientation) otherwise.

Support for axis orientation requires knowledge of the validity extent, which is not available in proj or WKT strings. So if we added support for flipped axis orientation, we‘d need to ask the user for the validity extent. You could do the math yourself to convert coordinates from `neu` to `swu` axis orientation easily though.

**Comment by JackClouseau** [comment]
If I use a proj string instead of the WKT, I can now get a more believable result.

Using the following proj string for 50N, 14E:
'+proj=krovak +axis=swu +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs +type=crs'

Produces the result:
[1048457.5530448752, 774047.4656886793]

Which is both the right axis order and non-negative.  This is better than the WKT result.
However, I would prefer to use the WKT instead of the proj string method.   Using the WKT with the current PROJ version (on a desktop test app) produces the correct result.

**Comment by ahocevar** [comment]
Which WKT string were you using? With
```
PROJCS["S-JTSK / Krovak",
    GEOGCS["S-JTSK",
        DATUM["System_of_the_Unified_Trigonometrical_Cadastral_Network",
            SPHEROID["Bessel 1841",6377397.155,299.1528128],
            TOWGS84[589,76,480,0,0,0,0]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4156"]],
    PROJECTION["Krovak"],
    PARAMETER["latitude_of_center",49.5],
    PARAMETER["longitude_of_center",24.8333333333333],
    PARAMETER["azimuth",30.2881397527778],
    PARAMETER["pseudo_standard_parallel_1",78.5],
    PARAMETER["scale_factor",0.9999],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","5513"]]
```
`gdaltransform` produces the same result as proj4js.

**Comment by ahocevar** [comment]
Most desktop GIS systems have access to the EPSG database. proj4js does not, and fully relies on the projection definitions. And yes, on epsg.io, only the proj string contains the axis information required to produce the results you desire. If you'd add the axis information to the WKT string, it would work as well.

I'm closing this, because it is a problem with the used projection definition, not with proj4js. If you feel there is still a problem, please open a new issue.
